name: Branch Operations

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - closed

jobs:
  sync-develop:
    name: Sync hotfix to develop
    if: >-
      github.event.before != '0000000000000000000000000000000000000000' &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "edamamenoko"
          git config user.email "mashold0802@gmail.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge changes into develop
        run: |
          git checkout develop
          git merge --no-ff ${{ github.ref_name }}
          git push origin develop

  delete-releaseSTG:
    name: Delete releaseSTG branch after merge to main
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.head.ref, 'releaseSTG') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "edamamenoko"
          git config user.email "mashold0802@gmail.com"

      - name: Delete releaseSTG branch
        run: |
          echo "Deleting the branch: ${{ github.event.pull_request.head.ref }}"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
