name: Branch Operations

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - closed

jobs:
  sync-develop:
    name: Sync hotfix to develop
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "edamamenoko"
          git config user.email "mashold0802@gmail.com"

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Checkout develop branch
        run: git checkout -B develop origin/develop

      - name: Merge changes into develop
        run: |
          git merge --no-ff origin/${{ github.event.pull_request.head.ref }} -X theirs
          git push origin develop
