name: Delete releaseSTG branch after merge to main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  delete-releaseSTG:
    name: Delete releaseSTG branch after merge to main
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'releaseSTG') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete releaseSTG branch
        run: |
          echo "Deleting the branch: ${{ github.event.pull_request.head.ref }}"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
